name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubicloud-standard-4-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: npm test
